### ISSUE TITLE
Test stopped working due to npm error

### ISSUE THREAD

**Issue by ramonfincken** [WordPress/phpunit-test-runner#144]
debug log attached

[2021-02-24T19_30_22_406Z-debug.log](https://github.com/WordPress/phpunit-test-runner/files/6038405/2021-02-24T19_30_22_406Z-debug.log)
cd '/home/wptestrun/prepare/tests/phpunit/data/plugins/'; unzip wordpress-importer.zip; rm wordpress-importer.zip
Archive:  wordpress-importer.zip
   creating: wordpress-importer/
  inflating: wordpress-importer/class-wp-import.php  
  inflating: wordpress-importer/compat.php  
   creating: wordpress-importer/parsers/
  inflating: wordpress-importer/parsers/class-wxr-parser.php  
  inflating: wordpress-importer/parsers/class-wxr-parser-regex.php  
  inflating: wordpress-importer/parsers/class-wxr-parser-simplexml.php  
  inflating: wordpress-importer/parsers/class-wxr-parser-xml.php  
  inflating: wordpress-importer/parsers.php  
  inflating: wordpress-importer/readme.txt  
  inflating: wordpress-importer/wordpress-importer.php  
cd '/home/wptestrun/prepare'; npm install && grunt build

> puppeteer@4.0.1 install /home/wptestrun/prepare/node_modules/grunt-contrib-qunit/node_modules/puppeteer
> node install.js

/home/wptestrun/prepare/node_modules/grunt-contrib-qunit/node_modules/puppeteer/install.js:178
            } catch {
                    ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm WARN notsup Unsupported engine for wp-prettier@2.0.5: wanted: {"node":">=10.13.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: wp-prettier@2.0.5
npm WARN notsup Unsupported engine for puppeteer-core@3.0.0: wanted: {"node":">=10.18.1"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: puppeteer-core@3.0.0
npm WARN notsup Unsupported engine for wp-prettier@2.2.1-beta-1: wanted: {"node":">=10.13.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: wp-prettier@2.2.1-beta-1
npm WARN notsup Unsupported engine for puppeteer-core@5.5.0: wanted: {"node":">=10.18.1"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: puppeteer-core@5.5.0
npm WARN notsup Unsupported engine for wp-prettier@2.2.1-beta-1: wanted: {"node":">=10.13.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: wp-prettier@2.2.1-beta-1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@4.0.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@4.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wptestrun/npm-cache/_logs/2021-02-24T19_30_22_406Z-debug.log
Error: Failed to perform operation.

**Comment by ramonfincken** [comment]
might be an npm version issue ..

**Comment by ramonfincken** [comment]
and so it was ..
